# Generated by Django 5.1.3 on 2024-11-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_control', models.CharField(max_length=150)),
                ('codigo_control', models.CharField(max_length=20)),
                ('estado_control', models.BooleanField(default=True)),
                ('conclusion_control', models.TextField()),
                ('descripcion_control', models.TextField()),
                ('frecuencia_control', models.CharField(max_length=20)),
                ('clasificacion_control', models.CharField(max_length=20)),
                ('tipologia_control', models.CharField(max_length=20)),
                ('descripcion_riesgo', models.TextField()),
                ('preventivo_detectivo', models.CharField(max_length=20)),
                ('objetivo_control', models.TextField()),
                ('año_control', models.IntegerField()),
                ('periodo_control', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validaciones_Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_validacion', models.CharField(max_length=150)),
                ('respuesta_validacion', models.CharField(blank=True, max_length=10)),
                ('explicacion_validacion', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_diseño', models.CharField(max_length=150)),
                ('comentarios_diseño', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('control_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.controles')),
            ],
        ),
        migrations.CreateModel(
            name='Encabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('total_horas_invertidas', models.IntegerField()),
                ('recursos_consultados', models.TextField()),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('control_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.controles')),
            ],
        ),
        migrations.CreateModel(
            name='Validaciones_Diseño_Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('diseño_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.diseño')),
                ('validaciones_diseño_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.validaciones_diseño')),
            ],
        ),
    ]
