# Generated by Django 5.1.3 on 2024-11-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='controles',
            name='auditor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auditoria.auditores'),
            preserve_default=False,
        ),
    ]
