# Generated by Django 5.1.3 on 2024-11-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditores_controles_auditor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controles',
            name='estado_control',
            field=models.CharField(max_length=20),
        ),
    ]
