# Generated by Django 5.1.3 on 2024-11-25 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_controles_estado_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='controles',
            old_name='auditor_id',
            new_name='auditor',
        ),
        migrations.RenameField(
            model_name='diseño',
            old_name='control_id',
            new_name='control',
        ),
        migrations.RenameField(
            model_name='encabezado',
            old_name='control_id',
            new_name='control',
        ),
        migrations.RenameField(
            model_name='validaciones_diseño_diseño',
            old_name='diseño_id',
            new_name='diseño',
        ),
        migrations.RenameField(
            model_name='validaciones_diseño_diseño',
            old_name='validaciones_diseño_id',
            new_name='validaciones_diseño',
        ),
        migrations.AddField(
            model_name='auditores',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
