# Generated by Django 5.1.3 on 2024-11-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_alter_auditores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='control',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diseño', to='auditoria.controles'),
        ),
        migrations.AlterField(
            model_name='encabezado',
            name='control',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encabezado', to='auditoria.controles'),
        ),
    ]
