# Generated by Django 5.1.3 on 2024-11-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_alter_diseño_control_alter_encabezado_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='fecha_ejecucion_prueba',
            field=models.DateField(null=True),
        ),
    ]
