# Generated by Django 5.1.3 on 2024-11-26 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_diseño_fecha_ejecucion_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezado',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encabezado',
            name='fecha_elaboracion',
            field=models.DateField(null=True),
        ),
    ]
