# Generated by Django 5.1.3 on 2024-11-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_encabezado_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validaciones_diseño',
            name='explicacion_validacion',
        ),
        migrations.RemoveField(
            model_name='validaciones_diseño',
            name='respuesta_validacion',
        ),
        migrations.AddField(
            model_name='validaciones_diseño_diseño',
            name='explicacion_validacion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validaciones_diseño_diseño',
            name='respuesta_validacion',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
