# Generated by Django 5.1.3 on 2024-11-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0010_alter_auditores_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='conclusion_diseño',
            field=models.CharField(default='Satisfactorio', max_length=20),
            preserve_default=False,
        ),
    ]
